name: "Tinc VPN Client"
description: "Open-source VPN daemon"
url: https://github.com/mdzidic/hassio-tinc-vpn-client
version: "0.0.1"
slug: "tinc"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
hassio_api: true
host_network: true
privileged:
  - NET_ADMIN
devices:
  - /dev/net/tun
options:
  client_name: client01
  private_key: paste-client-private-key-base64
schema:
  client_name: str
  private_key: str
